# Generated by Django 5.1.2 on 2024-10-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_images/'),
        ),
    ]
