# Generated by Django 5.1.2 on 2024-10-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_vendor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/logo_images/'),
        ),
    ]
