# Generated by Django 5.1.2 on 2024-11-07 10:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
